name: CI Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        if: always()
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting style
        run: npm run lint:ts
      - name: unit tests
        if: always()
        run: npm run test:unit
      - name: build storybook
        run: npm run sb:build
        if: always()
      - name: screnshot test
        run: npm run test:screen:ci
        if: always()

